[server]
# Where to bind
listen="192.168.0.15:8080"
# Remote access address
remote=""
# Allowed origins for CORS
allowedOrigins=["*"]
# Shell command to use when executing adapter's commands
shellCommand=["sh", "-c"]
# On windows, it should be
# shellCommand=["cmd", "/c"]
# Cache folder where stuff like widgets generated will be store
cachePath="cache"

[database]
# Urls of mongodb server
urls=["mongodb://127.0.0.1:27017/alfredo"]

[security]
# Secret key to use for signing auth token
secret="YourSecretKeyGoesHere"