[server]
# Where to bind
listen="192.168.0.15:8080"
# Wether you want to communicate via https
useHTTPS=false
# Remote access address
remote=""
# Allowed origins for CORS
allowedOrigins=["*"]
# Shell command to use when executing adapter's commands
shellCommand=["sh", "-c"]
# On windows, it should be
# shellCommand=["cmd", "/c"]
# Log level used by the server logger
logLevel="debug"
# Allow new controller to register to this instance
allowRegistering=true
# Path to the adapters json file
adaptersPath="./adapters/adapters.json"

[database]
# Urls of mongodb server
urls=["mongodb://127.0.0.1:27017/alfredo"]

[security]
# Secret key to use for signing auth token
secret="YourSecretKeyGoesHere"